CREATE USER ${DB_REPL_USER} REPLICATION LOGIN PASSWORD '${DB_REPL_PASSWORD}';

CREATE DATABASE ${DB_DATABASE};

\c ${DB_DATABASE};


CREATE TABLE IF NOT EXISTS Phones (
    id SERIAL PRIMARY KEY,
    Phone VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS Emails (
    id SERIAL PRIMARY KEY,
    Email VARCHAR(100) NOT NULL
);

INSERT INTO Emails (Email) VALUES ('aboba@google.com'), ( 'aboba@ya.ru');
INSERT INTO Phones (Phone) VALUES ('+7 (800) 555 35 35'), ('8 800 555 35 35');

